### PR TITLE
Cherry-pick into Refactor plus Fix a promote bug

### LINKED ISSUE #26: Tests fail since README example fails
I added the README example as a test in https://github.com/SciML/SparsityDetection.jl/commit/2a89e1f478a489fb57eccba23c3d3d0712641451 because from SparseDiffTools.jl I could see it's failing on the current release.

### LINKED ISSUE #148: SparsityDetection bug in 02_advanced_ODE_solving notebook
Running:

using SparsityDetection, SparseArrays
input = rand(32,32,2)
output = similar(input)
sparsity_pattern = sparsity!(brusselator_2d_loop,output,input,p,0.0)
jac_sparsity = Float64.(sparse(sparsity_pattern))

throws the following error:

┌ Info: Precompiling SparsityDetection [684fba80-ace3-11e9-3d08-3bc7ed6f96df]
└ @ Base loading.jl:1260
MethodError: no method matching iterate(::Tuple{DataType,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}, ::Tuple{DataType,Int64})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector, ::Any) at essentials.jl:603
  iterate(!Matched::ExponentialBackOff, ::Any) at error.jl:253
  iterate(!Matched::Base.MethodList, ::Any...) at reflection.jl:854
  ...

Stacktrace:
 [1] call at C:\Users\Denis\.julia\packages\Cassette\7OymZ\src\context.jl:451 [inlined]
 [2] fallback at C:\Users\Denis\.julia\packages\Cassette\7OymZ\src\context.jl:448 [inlined]
 [3] recurse(::Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}, ::typeof(iterate), ::Cassette.Tagged{Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},Tuple{DataType,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}},Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:ref, :step, :len, :offset),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:hi, :lo),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:hi, :lo),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}}},Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}}, ::Tuple{DataType,Int64}) at C:\Users\Denis\.julia\packages\Cassette\7OymZ\src\overdub.jl:486
 [4] overdub(::Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}, ::Function, ::Cassette.Tagged{Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},Tuple{DataType,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}},Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:ref, :step, :len, :offset),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:hi, :lo),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:hi, :lo),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}}},Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}}, ::Tuple{DataType,Int64}) at C:\Users\Denis\.julia\packages\SparsityDetection\Q6Utm\src\sparsity_tracker.jl:134
 [5] (::SparsityDetection.var"#8#9"{Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks},typeof(iterate)})(::Cassette.Tagged{Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},Tuple{DataType,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}},Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:ref, :step, :len, :offset),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:hi, :lo),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:hi, :lo),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}}},Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}}, ::Vararg{Any,N} where N) at C:\Users\Denis\.julia\packages\Cassette\7OymZ\src\context.jl:262
 [6] overdub(::Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}, ::typeof(Core._apply_iterate), ::Function, ::Function, ::Cassette.Tagged{Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},Tuple{DataType,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}},Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:ref, :step, :len, :offset),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:hi, :lo),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NamedTuple{(:hi, :lo),Tuple{Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}},Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}}}}}},Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}}, ::Tuple{Int64}) at C:\Users\Denis\.julia\packages\Cassette\7OymZ\src\context.jl:262
 [7] checkbounds at .\abstractarray.jl:502 [inlined]
 [8] overdub at C:\Users\Denis\.julia\packages\SparsityDetection\Q6Utm\src\sparsity_tracker.jl:134 [inlined]
 [9] getindex at .\range.jl:641 [inlined]
 [10] recurse(::Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}, ::typeof(getindex), ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Int64) at C:\Users\Denis\.julia\packages\Cassette\7OymZ\src\overdub.jl:0
 [11] overdub(::Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}, ::Function, ::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Int64) at C:\Users\Denis\.julia\packages\SparsityDetection\Q6Utm\src\sparsity_tracker.jl:134
 [12] brusselator_2d_loop at .\In[11]:10 [inlined]
 [13] recurse(::Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}, ::typeof(brusselator_2d_loop), ::Cassette.Tagged{Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},Array{Float64,3},Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Array{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta},3},Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}}, ::Cassette.Tagged{Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},Array{Float64,3},Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Array{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta},3},Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}}, ::Cassette.Tagged{Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},NTuple{4,Float64},Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},NTuple{4,Cassette.Immutable{Cassette.Meta{Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta}}},Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}}, ::Cassette.Tagged{Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},Float64,Union{SparsityDetection.Input, SparsityDetection.Output, SparsityDetection.ProvinanceSet},Cassette.NoMetaMeta,Cassette.Context{SparsityDetection.var"##SparsityContext#Name",Tuple{Sparsity,SparsityDetection.Path},Cassette.Tag{SparsityDetection.var"##SparsityContext#Name",0x4e07e39148336526,Nothing},SparsityDetection.var"##PassType#253",IdDict{Module,Dict{Symbol,Cassette.BindingMeta}},Cassette.DisableHooks}}) at C:\Users\Denis\.julia\packages\Cassette\7OymZ\src\overdub.jl:0
 [14] sparsity!(::Function, ::Array{Float64,3}, ::Array{Float64,3}, ::NTuple{4,Float64}, ::Vararg{Any,N} where N; sparsity::Sparsity, verbose::Bool) at C:\Users\Denis\.julia\packages\SparsityDetection\Q6Utm\src\program_sparsity.jl:29
 [15] sparsity!(::Function, ::Array{Float64,3}, ::Array{Float64,3}, ::NTuple{4,Float64}, ::Vararg{Any,N} where N) at C:\Users\Denis\.julia\packages\SparsityDetection\Q6Utm\src\program_sparsity.jl:23
 [16] top-level scope at In[12]:4

### PR DESCRIPTION
**Pull request by shashi**
Fixes https://github.com/SciML/DiffEqTutorials.jl/issues/148 fixes https://github.com/SciML/SparsityDetection.jl/issues/26

### CODE REVIEW

File: src/SparsityDetection.jl [hunk 1]
```diff
@@ -6,16 +6,17 @@ using Cassette: tag, untag, Tagged, metadata, hasmetadata, istagged, canrecurse
...
+include("util.jl")
+include("controlflow.jl")
+include("propagate_tags.jl")
 include("linearity.jl")
+include("jacobian.jl")
 include("hessian.jl")
 include("blas.jl")
-include("linearity_special.jl")
+
+sparsity!(args...; kwargs...) = jacobian_sparsity(args...; kwargs...)
```
Comment (ChrisRackauckas) [inline src/SparsityDetection.jl:19]: what's this?

File: src/blas.jl [hunk 2]
```diff
@@ -1,22 +1,15 @@
...
-@reroute LinearAlgebra.BLAS.dot LinearAlgebra.dot(Any, Any)
-@reroute LinearAlgebra.BLAS.axpy! LinearAlgebra.axpy!(Any,
+@reroute LinearAlgebra.BLAS.dot(x,y) LinearAlgebra.dot(Any, Any)
+@reroute LinearAlgebra.BLAS.axpy!(x, y) LinearAlgebra.axpy!(Any,
                                                       AbstractArray,
                                                       AbstractArray)
+
+gengemv!(tA, α, A, x, β, y) = LinearAlgebra.generic_matvecmul!(y, tA, A, x, LinearAlgebra.MulAddMul(α, β))
+
+@reroute LinearAlgebra.BLAS.gemv!(tA, α, A, x, β, y) gengemv!(Any, Any, Any, Any, Any, Any)
```
Comment (ChrisRackauckas) [inline src/blas.jl]: How would one deal with argument order differences here?

Comment (ChrisRackauckas) [reply src/blas.jl]: Oh I see, just define a function like above. Simple. Awesome.

File: src/hessian.jl [hunk 3]
```diff
@@ -1,78 +1,117 @@
...
+# TermCombination datastructure
 
-const TaggedOf{T} = Tagged{A, T} where A
+struct TermCombination
+    terms::Set{Dict{Int, Int}} # idx => pow
+end
 
-const HTagType = Union{Input, TermCombination}
-Cassette.metadatatype(::Type{<:HessianSparsityContext}, ::DataType) = HTagType
+@eval Base.zero(::Type{TermCombination}) = $(TermCombination(Set{Dict{Int,Int}}()))
```
Comment (ChrisRackauckas) [inline src/hessian.jl:7]: what's the reason for this being an eval?

File: src/SparsityDetection.jl (hunk 1 above)
Comment (shashi) [reply src/SparsityDetection.jl:19]: There was a `@deprecate` here, but I removed it.

**Comment by shashi** [comment]
I have a commit which merges this to master, waiting for CI to push it.

File: src/hessian.jl (hunk 3 above)
Comment (shashi) [reply src/hessian.jl:7]: So that it's not creating a Set every time it's called. This creates a singleton. All operations on TermCombination are pure.

File: src/SparsityDetection.jl (hunk 1 above)
Comment (shashi) [reply src/SparsityDetection.jl:19]: Should I put it back? I figured it does no one any harm if we use sparsity! and hsparsity

Comment (ChrisRackauckas) [reply src/SparsityDetection.jl:19]: No, it's fine to change, I was just wondering what was going on there. Let's make sure the SparseDiffTools, DifferentialEquations docs, and this repo's README all get updated for this.
